#' @import shiny
ui <- fluidPage(

  titlePanel("Probabilistic Cause-of-death Assignment using Verbal Autopsies"),
  p("Developed by Tyler McCormick ", (a(href="mailto:tylermc@uw.edu", "(tylermc@uw.edu)")),
    "Zehang Richard Li ", (a(href="mailto:lizehang@uw.edu", "(lizehang@uw.edu)")),
    "and Samuel Clark ", a(href="mailto:work@samclark.net ", "(work@samclark.net)")),
  p("The complete study can be viewed ", a(href="http://arxiv.org/abs/1411.3042", "here")),
  hr(),
  shinyjs::useShinyjs(),

  sidebarLayout(
    sidebarPanel(
      fileInput("readIn",
                "Upload your own data here",
                multiple = FALSE,
                accept = NULL),
      h3("Choose your preferences"),
      br(),
      checkboxInput("byAll", "Include an analysis of all records?", TRUE),
      checkboxInput("bySex", "Include sex-specific results?", FALSE),
      checkboxInput("byAge", "Include age-specific results (infant, child, adult)?", FALSE),
      sliderInput(inputId="topDeaths", label="Number of causes to include in summaries/plots", min=5, max=20, value=10),
      selectInput(inputId="algorithm", label="Select Algorithm:",
                  choices=c("InSilicoVA" = "InSilicoVA",
                            "InterVA5" = "InterVA5"),
                  width="150px"),
      conditionalPanel(condition="input.algorithm=='InSilicoVA'",
                       sliderInput(inputId="simLength", label="Number of iterations in the simulation", min=300, max=7000, value=5000)),
      conditionalPanel(condition="input.algorithm=='InterVA5'",
                       selectInput(inputId="HIV", label="Level of HIV prevalence",
                                   choices=c("v (very low: < 0.01% of all deaths)" = "v",
                                             "l (low:  ~ 0.1% of all deaths)" = "l",
                                             "h (high: >= 1% of all deaths)" = "h"), width="300px")),
      conditionalPanel(condition="input.algorithm=='InterVA5'",
                       selectInput(inputId="Malaria", label="Level of malaria prevalence",
                                   choices=c("v (very low: < 0.01% of all deaths)" = "v",
                                             "l (low:  ~ 0.1% of all deaths)" = "l",
                                             "h (high: >= 1% of all deaths)" = "h"), width="300px")),
      #br(),
      #h4("Data Checks"),
      checkboxInput("odkBC", "Are the data from an ODKBriefcase export?", TRUE),

      conditionalPanel("output.fileUploaded", actionButton("processMe", "Analyze my data!"))#,
      # hr(),
      # helpText("Downloads will be available once the data have been analyzed"),
      # downloadButton("downloadAgeDist", "Download Plot of Age Distribution as .pdf"), br(), br(),
      # downloadButton("downloadCOD1", "Download Causes for All Records as .csv"), br(),
      # downloadButton("downloadData1", "Download Summary for All Records as .csv"), br(),
      # downloadButton("downloadPlot1", "Download Plot for All Records as .pdf"), br(), br(),
      # ##
      # downloadButton("downloadCOD2", "Download Causes for all Males as .csv"), br(),
      # downloadButton("downloadData2", "Download Summary for Males as .csv"),
      # downloadButton("downloadPlot2", "Download Plot for Males as .pdf"), br(), br(),
      # ##
      # downloadButton("downloadCOD3", "Download Causes for all Females as .csv"), br(),
      # downloadButton("downloadData3", "Download Summary for Females as .csv"),
      # downloadButton("downloadPlot3", "Download Plot for Females as .pdf"), br(), br(),
      # ##
      # downloadButton("downloadCOD4", "Download  Causes for all Neonates as .csv"), br(),
      # downloadButton("downloadData4", "Download Summary for Neonates as .csv"),
      # downloadButton("downloadPlot4", "Download Plot for Neonates as .pdf"), br(), br(),
      # ##
      # downloadButton("downloadCOD5", "Download Causes for all Children as .csv"), br(),
      # downloadButton("downloadData5", "Download Summary for Children as .csv"),
      # downloadButton("downloadPlot5", "Download Plot for Children as .pdf"), br(), br(),
      # ##
      # downloadButton("downloadCOD6", "Download Causes for all Adults as .csv"), br(),
      # downloadButton("downloadData6", "Download Summary for Adults as .csv"),
      # downloadButton("downloadPlot6", "Download Plot for Adults as .pdf"), br(), br(),
      # ##
      # downloadButton("downloadWarnings", "Download warnings as .txt")
    ),

    ## Outputs
    mainPanel(
      tabsetPanel(type = "tabs",
                  tabPanel(title = "All",
                           h4(textOutput("titleDescriptiveStatsAll")),
                           tableOutput("descriptiveStatsAll"),
                           h4(textOutput("titleSummaryAll")),
                           verbatimTextOutput("summaryAll"),
                           h4(textOutput("titlePlotAll")),
                           plotOutput("plotAll")),
                  tabPanel(title = "Male",
                           h4(textOutput("titleDescriptiveStatsMale")),
                           tableOutput("descriptiveStatsMale"),
                           h4(textOutput("titleSummaryMale")),
                           verbatimTextOutput("summaryMale"),
                           h4(textOutput("titlePlotMale")),
                           plotOutput("plotMale")),
                  tabPanel(title = "Female",
                           h4(textOutput("titleDescriptiveStatsFemale")),
                           tableOutput("descriptiveStatsFemale"),
                           h4(textOutput("titleSummaryFemale")),
                           verbatimTextOutput("summaryFemale"),
                           h4(textOutput("titlePlotFemale")),
                           plotOutput("plotFemale")),
                  tabPanel(title = "Neonate",
                           h4(textOutput("titleDescriptiveStatsNeonate")),
                           tableOutput("descriptiveStatsNeonate"),
                           h4(textOutput("titleSummaryNeonate")),
                           verbatimTextOutput("summaryNeonate"),
                           h4(textOutput("titlePlotNeonate")),
                           plotOutput("plotNeonate")),
                  tabPanel(title = "Child",
                           h4(textOutput("titleDescriptiveStatsChild")),
                           tableOutput("descriptiveStatsChild"),
                           h4(textOutput("titleSummaryChild")),
                           verbatimTextOutput("summaryChild"),
                           h4(textOutput("titlePlotChild")),
                           plotOutput("plotChild")),
                  tabPanel(title = "Adult",
                           h4(textOutput("titleDescriptiveStatsAdult")),
                           tableOutput("descriptiveStatsAdult"),
                           h4(textOutput("titleSummaryAdult")),
                           verbatimTextOutput("summaryAdult"),
                           h4(textOutput("titlePlotAdult")),
                           plotOutput("plotAdult")),
                  tabPanel(title = "Download Results",
                           br(),
                           downloadButton("downloadAgeDist", "Download Plot of Age Distribution (.pdf)"),
                           br(), br(),
                           fluidRow(
                             column(4, "Results for All Records"),
                             column(4, "Results for Male Records"),
                             column(4, "Results for Female Records")), 
                           column(12, br()),
                           fluidRow(
                             column(4, downloadButton("downloadCOD1", "Causes of Death (.csv)")),
                             column(4, downloadButton("downloadCOD2", "Causes of Death (.csv)")),
                             column(4, downloadButton("downloadCOD3", "Causes of Death (.csv)"))),
                           fluidRow(
                             column(4, downloadButton("downloadData1", "Summary Table (.csv)")),
                             column(4, downloadButton("downloadData2", "Summary Table (.csv)")),
                             column(4, downloadButton("downloadData3", "Summary Table (.csv)"))),
                           fluidRow(
                             column(4, downloadButton("downloadPlot1", "Plot (.pdf)")),
                             column(4, downloadButton("downloadPlot2", "Plot (.pdf)")),
                             column(4, downloadButton("downloadPlot3", "Plot (.pdf)"))),
                           column(12, br()),
                           fluidRow(
                             column(4, "Results for Neonate Records"),
                             column(4, "Results for Child Records"),
                             column(4, "Results for Adult Records")),
                           fluidRow(
                             column(4, downloadButton("downloadCOD4", "Causes of Death (.csv)")),
                             column(4, downloadButton("downloadCOD5", "Causes of Death (.csv)")),
                             column(4, downloadButton("downloadCOD6", "Causes of Death (.csv)"))),
                           fluidRow(
                             column(4, downloadButton("downloadData4", "Summary Table (.csv)")),
                             column(4, downloadButton("downloadData5", "Summary Table (.csv)")),
                             column(4, downloadButton("downloadData6", "Summary Table (.csv)"))),
                           fluidRow(
                             column(4, downloadButton("downloadPlot4", "Plot (.pdf)")),
                             column(4, downloadButton("downloadPlot5", "Plot (.pdf)")),
                             column(4, downloadButton("downloadPlot6", "Plot (.pdf)")))
                  )
      )
    )
  )
)
