#' @import shiny
ui <- fluidPage(

  titlePanel("Analyze Verbal Autopsy Data with openVA"),
  p("Developed by the openVA team", a(href="https://openva.net", "(https://openVA.net)")),
  p("This work is supported by: National Institutes of Health,",
    "WHO Reference Group for Verbal Autopsy,",
    "Data for Health and Vital Strategies",
    HTML("<br>"),
    tags$a(img(src="d4h.jpg", style="width:100px"), href="https://www.bloomberg.org/program/public-health/data-health/"),
    HTML("&emsp;"),
    tags$a(img(src="vital_strategies.png", style="width:100px"), href="https://www.vitalstrategies.org/")),
  hr(),
  shinyjs::useShinyjs(),

  sidebarLayout(
    sidebarPanel(
      fileInput("readIn",
                "Upload your own data here",
                multiple = FALSE,
                accept = NULL),
      h3("Choose your preferences"),
      br(),
      checkboxInput("byAll", "Include an analysis of all records?", TRUE),
      checkboxInput("bySex", "Include sex-specific results?", FALSE),
      checkboxInput("byAge", "Include age-specific results (infant, child, adult)?", FALSE),
      sliderInput(inputId="topDeaths", label="Number of causes to include in summaries/plots", min=5, max=20, value=10),
      selectInput(inputId="algorithm", label="Select Algorithm:",
                  choices=c("InSilicoVA" = "InSilicoVA",
                            "InterVA5" = "InterVA5",
                            "Tariff2" = "Tariff2"),
                  width="150px"),
      conditionalPanel(condition="input.algorithm=='InSilicoVA'",
                       sliderInput(inputId="simLength", label="Number of iterations in the simulation", min=300, max=7000, value=5000, step = 100)),
      conditionalPanel(condition="input.algorithm=='InterVA5'",
                       selectInput(inputId="HIV", label="Level of HIV prevalence",
                                   choices=c("v (very low: < 0.01% of all deaths)" = "v",
                                             "l (low:  ~ 0.1% of all deaths)" = "l",
                                             "h (high: >= 1% of all deaths)" = "h"), width="300px")),
      conditionalPanel(condition="input.algorithm=='InterVA5'",
                       selectInput(inputId="Malaria", label="Level of malaria prevalence",
                                   choices=c("v (very low: < 0.01% of all deaths)" = "v",
                                             "l (low:  ~ 0.1% of all deaths)" = "l",
                                             "h (high: >= 1% of all deaths)" = "h"), width="300px")),
      conditionalPanel(condition="input.algorithm=='Tariff2'",
                       selectInput(inputId = "svaCountry", label = "Country",
                                   choices = openVAapp:::smartVA_countries(),
                                   width="300px")),
      conditionalPanel(condition="input.algorithm=='Tariff2'",
                       checkboxInput("svaHIV", "HIV region", FALSE)),
      conditionalPanel(condition="input.algorithm=='Tariff2'",
                       checkboxInput("svaMalaria", "Malaria region", FALSE)),
      conditionalPanel(condition="input.algorithm=='Tariff2'",
                       checkboxInput("svaHCE", "Use health care experience variables", TRUE)),
      conditionalPanel(condition="input.algorithm=='Tariff2'",
                       checkboxInput("svaFreeText", "Use 'free text' variables", TRUE)),
      br(),
      h4("Data format"),
      checkboxInput("odkBC", "Are the data from an ODKBriefcase export?", TRUE),

      conditionalPanel("output.fileUploaded", actionButton("processMe", "Analyze my data!"))
    ),
    ## Outputs
    mainPanel(
      tabsetPanel(type = "tabs",
                  tabPanel(title = "All",
                           h4(textOutput("titleDescriptiveStatsAll")),
                           tableOutput("descriptiveStatsAll"),
                           h4(textOutput("titleSummaryAll")),
                           verbatimTextOutput("summaryAll"),
                           h4(textOutput("titlePlotAll")),
                           plotOutput("plotAll")),
                  tabPanel(title = "Male",
                           h4(textOutput("titleDescriptiveStatsMale")),
                           tableOutput("descriptiveStatsMale"),
                           h4(textOutput("titleSummaryMale")),
                           verbatimTextOutput("summaryMale"),
                           h4(textOutput("titlePlotMale")),
                           plotOutput("plotMale")),
                  tabPanel(title = "Female",
                           h4(textOutput("titleDescriptiveStatsFemale")),
                           tableOutput("descriptiveStatsFemale"),
                           h4(textOutput("titleSummaryFemale")),
                           verbatimTextOutput("summaryFemale"),
                           h4(textOutput("titlePlotFemale")),
                           plotOutput("plotFemale")),
                  tabPanel(title = "Neonate",
                           h4(textOutput("titleDescriptiveStatsNeonate")),
                           tableOutput("descriptiveStatsNeonate"),
                           h4(textOutput("titleSummaryNeonate")),
                           verbatimTextOutput("summaryNeonate"),
                           h4(textOutput("titlePlotNeonate")),
                           plotOutput("plotNeonate")),
                  tabPanel(title = "Child",
                           h4(textOutput("titleDescriptiveStatsChild")),
                           tableOutput("descriptiveStatsChild"),
                           h4(textOutput("titleSummaryChild")),
                           verbatimTextOutput("summaryChild"),
                           h4(textOutput("titlePlotChild")),
                           plotOutput("plotChild")),
                  tabPanel(title = "Adult",
                           h4(textOutput("titleDescriptiveStatsAdult")),
                           tableOutput("descriptiveStatsAdult"),
                           h4(textOutput("titleSummaryAdult")),
                           verbatimTextOutput("summaryAdult"),
                           h4(textOutput("titlePlotAdult")),
                           plotOutput("plotAdult")),
                  tabPanel(title = "Download Results",
                           br(),
                           column(12, "Downloads are available after data have been analyzed"),
                           br(),
                           downloadButton("downloadMetadata", "Download Metadata Used to Produce Results (.csv)"),
                           br(),
                           downloadButton("downloadAgeDist", "Download Plot of Age Distribution (.pdf)"),
                           br(), br(),
                           fluidRow(
                             column(4, "Results for All Records"),
                             column(4, "Results for Male Records"),
                             column(4, "Results for Female Records")), 
                           column(12, br()),
                           fluidRow(
                             column(4, downloadButton("downloadCOD1", "Causes of Death (.csv)")),
                             column(4, downloadButton("downloadCOD2", "Causes of Death (.csv)")),
                             column(4, downloadButton("downloadCOD3", "Causes of Death (.csv)"))),
                           fluidRow(
                             column(4, downloadButton("downloadData1", "Summary Table (.csv)")),
                             column(4, downloadButton("downloadData2", "Summary Table (.csv)")),
                             column(4, downloadButton("downloadData3", "Summary Table (.csv)"))),
                           fluidRow(
                             column(4, downloadButton("downloadPlot1", "Plot (.pdf)")),
                             column(4, downloadButton("downloadPlot2", "Plot (.pdf)")),
                             column(4, downloadButton("downloadPlot3", "Plot (.pdf)"))),
                           fluidRow(
                             column(4, downloadButton("downloadWarnings1", "Warning Messages (.txt)")),
                             column(4, downloadButton("downloadWarnings2", "Warning Messages (.txt)")),
                             column(4, downloadButton("downloadWarnings3", "Warning Messages (.txt)"))),
                           column(12, br()),
                           fluidRow(
                             column(4, "Results for Neonate Records"),
                             column(4, "Results for Child Records"),
                             column(4, "Results for Adult Records")),
                           fluidRow(
                             column(4, downloadButton("downloadCOD4", "Causes of Death (.csv)")),
                             column(4, downloadButton("downloadCOD5", "Causes of Death (.csv)")),
                             column(4, downloadButton("downloadCOD6", "Causes of Death (.csv)"))),
                           fluidRow(
                             column(4, downloadButton("downloadData4", "Summary Table (.csv)")),
                             column(4, downloadButton("downloadData5", "Summary Table (.csv)")),
                             column(4, downloadButton("downloadData6", "Summary Table (.csv)"))),
                           fluidRow(
                             column(4, downloadButton("downloadPlot4", "Plot (.pdf)")),
                             column(4, downloadButton("downloadPlot5", "Plot (.pdf)")),
                             column(4, downloadButton("downloadPlot6", "Plot (.pdf)"))),
                           fluidRow(
                             column(4, downloadButton("downloadWarnings4", "Warning Messages (.txt)")),
                             column(4, downloadButton("downloadWarnings5", "Warning Messages (.txt)")),
                             column(4, downloadButton("downloadWarnings6", "Warning Messages (.txt)")))
                  )
      )
    )
  )
)
